networks:
    ethmainnet:
        description: Ethereum mainnet
        type: ethereum
        networkid: 0
        url: ws://my.ethchain.dnp.dappnode.eth:8546 

# alerts are tiggered if (from==address || to==address)

accounts:
    # simple account monitor, from or to
    0x137d9174d3bd00f2153dcc0fe7af712d3876a71e:
        network : ethmainnet

alerts:

    createSiringAuction:
        network : ethmainnet
        logs: false
        rule: (to == '0x06012c8cf97bead5deae237070f9587f8e7a266d' && data =~ '0xf7d8c883')
        message: createSiringAuction called with gas {{ .gasprice }}

    deepanalisys:
        network : ethmainnet
        logs: true
        rule: (log_0x7d1335Af903ff256823c9AA2d4a5aaA41E054335_0x6e812926864597b1b871e35c4b24bd297ec1e96c871c41b9d7d3deb47bbe751c =~ '0xf7d8c883')
        message: createSiringAuction called with gas {{ .gasprice }}
